CREATE TABLE `users` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`username` VARCHAR(255) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL COMMENT '
',
	`email` VARCHAR(255) NOT NULL,
	`displayName` VARCHAR(255) NOT NULL,
	`avartarUrl` VARCHAR(255),
	PRIMARY KEY(`id`)
);
